import React, { useState, useMemo } from "react";
import Papa from "papaparse";
import type { ParseResult } from "papaparse";

type ColumnGovernance = {
    column: string;
    dataType: string;
    nullable: string;
    classification: string;
    masking: string;
    hash: boolean;
    encrypt: boolean;
};

const dataTypeOptions = [
    "varchar(255)",
    "varchar(100)",
    "varchar(50)",
    "varchar(25)",
    "number",
    "number(38,7)",
    "number(15,2)",
    "timestamp_ntz",
    "date",
    "boolean",
    "float",
    "variant",
    "NUMBER GENERATED BY DEFAULT AS IDENTITY"
];

const maskingOptions = [
    "NONE",
    "email_mask_policy",
    "ssn_mask_policy",
    "card_mask_policy"
];

const nullableOptions = [
    "NULL",
    "NOT NULL"
]

const classificationOptions = ["NONE", "PII", "SENSITIVE", "FINANCIAL"];

const cdcOptions = [
    "Incremental_Load",
    "Changes_With_Deletes",
    "Changes_Without_Deletes",
    "RealTime_Changes_With_Deletes",
    "RealTime_Changes_Without_Deletes",
    "Real_Time_Incremental_Load",
    "Full_Load"
];

const allowedTypePattern =
    /^(varchar\(\d+\)|number(\(\d+,\d+\))?|timestamp_ntz|date|boolean|float|variant|NUMBER GENERATED BY DEFAULT AS IDENTITY)$/i;

function toSnakeCase(str: string) {
    return str
        .replace(/[^\w\s]/g, "")
        .replace(/\s+/g, "_")
        .replace(/([a-z0-9])([A-Z])/g, "$1_$2")
        .toLowerCase();
}

const detectPII = (column: string) => {
    const col = column.toLowerCase();
    if (col.includes("email"))
        return { classification: "PII", masking: "email_mask_policy" };
    if (col.includes("ssn"))
        return { classification: "PII", masking: "ssn_mask_policy" };
    if (col.includes("card"))
        return { classification: "PII", masking: "card_mask_policy" };
    return { classification: "NONE", masking: "NONE" };
};

function getTodayFormatted() {
    const today = new Date();
    return `${today.getFullYear()}_${String(
        today.getMonth() + 1
    ).padStart(2, "0")}_${String(today.getDate()).padStart(2, "0")}`;
}

function downloadFile(filename: string, content: string) {
    const blob = new Blob([content], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = filename;
    a.click();
    URL.revokeObjectURL(url);
}

export default function TableContractGenerator() {
    const [schema, setSchema] = useState("");
    const [tableName, setTableName] = useState("");
    const [rawColumns, setRawColumns] = useState("");
    const [formattedColumns, setFormattedColumns] = useState("");
    const [fileName, setFileName] = useState("");
    const [cdcType, setCdcType] = useState("Incremental_Load");

    const [governanceOverrides, setGovernanceOverrides] =
        useState<Record<string, ColumnGovernance>>({});

    const [primaryKeys, setPrimaryKeys] = useState<string[]>([]);
    const [warnings, setWarnings] = useState<string[]>([]);
    const [jsonOutput, setJsonOutput] = useState("");
    const [mappingOutput, setMappingOutput] = useState("");
    const [silverSQLOutput, setsilverSQLOutput] = useState("");
    const [silverViewSQLOutput, setsilverViewSQLOutput] = useState("");
    const [activeTab, setActiveTab] = useState<"json" | "mapping" | "ddl" | "view">(
        "json"
    );

    const tableIdColumn = tableName ? `${toSnakeCase(tableName)}_id` : "";

    const rawColumnList = useMemo(() => {
        return rawColumns.split(/[\n,]+/).map(c => c.trim()).filter(Boolean);
    }, [rawColumns]);

    const formattedColumnList = useMemo(() => {
        return formattedColumns.split("\n").map(c => c.trim()).filter(Boolean);
    }, [formattedColumns]);

    const governance = useMemo(() => {
        return formattedColumnList.map(col => {
            const override = governanceOverrides[col] || {};
            const piiDefaults = detectPII(col);

            return {
                column: col,
                dataType:
                    col === tableIdColumn
                        ? "NUMBER GENERATED BY DEFAULT AS IDENTITY"
                        : override.dataType || "",
                nullable: override.nullable || "NULL",
                classification:
                    override.classification || piiDefaults.classification,
                masking:
                    override.masking || piiDefaults.masking,
                hash: override.hash || false,
                encrypt: override.encrypt || false
            };
        });
    }, [formattedColumnList, governanceOverrides, tableIdColumn]);

    const effectivePrimaryKey = primaryKeys || tableIdColumn;

    const handleFormatColumns = () => {
        const formatted = rawColumnList.map(col => toSnakeCase(col));
        const unique = Array.from(new Set(formatted));
        const finalList = tableIdColumn ? [tableIdColumn, ...unique, "data_source"].filter(Boolean) : unique;

        setFormattedColumns(finalList.join("\n"));
        setPrimaryKeys([tableIdColumn]);
    };

    const handleFileUpload = async (
        event: React.ChangeEvent<HTMLInputElement>
    ) => {
        const file = event.target.files?.[0];
        if (!file) return;

        const extension = file.name.split(".").pop()?.toLowerCase();
        if (!["csv", "txt"].includes(extension || "")) {
            alert("Only CSV or TXT files are supported.");
            return;
        }

        setFileName(file.name);

        if (extension === "csv" || extension === "txt") {
            Papa.parse<string[]>(file, {
                preview: 1,
                skipEmptyLines: true,
                complete: (results: ParseResult<string[]>) => {
                    if (!results.data.length) return;

                    const headers = results.data[0];
                    const normalized = Array.from(
                        new Set(headers.map(h => toSnakeCase(h)).filter(Boolean))
                    );

                    const finalList = [
                        tableIdColumn,
                        ...normalized,
                        "data_source"
                    ].filter(Boolean);

                    setRawColumns(headers.join("\n"));
                    setFormattedColumns(finalList.join("\n"));
                    setPrimaryKeys([tableIdColumn]);
                }
            });

        }

        else {
            alert("Only CSV or TXT files are supported.");
        }

    };

    const validateBeforeGenerate = () => {
        const issues: string[] = [];
        const seen = new Set<string>();

        formattedColumnList.forEach(col => {
            if (seen.has(col)) issues.push(`Duplicate column: ${col}`);
            seen.add(col);
        });

        governance.forEach(col => {
            if (!col.dataType)
                issues.push(`Missing data type for ${col.column}`);
            else if (
                col.column !== tableIdColumn &&
                !allowedTypePattern.test(col.dataType)
            )
                issues.push(`Invalid data type for ${col.column}: ${col.dataType}`);
        });

        if (!effectivePrimaryKey)
            issues.push("Primary key must be selected.");

        if (!schema)
            issues.push("Schema must be entered.");

        if (!tableName)
            issues.push("Table must be entered.");

        setWarnings(issues);
        return issues.length === 0;
    };

    const handleGenerate = () => {
        if (!validateBeforeGenerate()) return;

        const snakeSchema = toSnakeCase(schema);
        const snakeTable = toSnakeCase(tableName);

        const jsonObject = {
            contract_version: "1.0",
            table: {
                schema: snakeSchema,
                name: snakeTable,
                primary_key: primaryKeys,
                cdc_type: cdcType
            },
            ingestion_governance: {
                data_source_column: "data_source",
                data_source_value: fileName
            },
            columns: governance
        };

        setJsonOutput(JSON.stringify(jsonObject, null, 2));

        const mappingLines = governance
            .filter(c => c.column !== "data_source" && c.column !== tableIdColumn)
            .map((col, index) => {
                const raw = rawColumnList[index] || col.column;
                return `("${raw}", "string", "${col.column}", "${col.dataType}")`;
            });

        setMappingOutput(`{\n  ${mappingLines.join(",\n  ")}\n}`);

        const ddlColumns = governance
            .map(col => `  ${col.column} ${col.dataType} ${col.nullable}`)
            .join(",\n");

        setsilverSQLOutput(
            `if not exists (\n
                select top 1 1 \n
                from information_schema.tables t \n
                where t.table_schema = '${snakeSchema}' \n
                and t.table_name = '${snakeTable}' \n
            )\n
            begin \n
            \n
                print('Creating table ${snakeSchema}.${snakeTable}'); \n
                \n
                CREATE TABLE ${snakeSchema}.${snakeTable} (\n${ddlColumns}\n);
                \n
            end`
        );

        setsilverViewSQLOutput(
            `
            declare @update_date varchar(10)
            declare @tracker varchar(20)
            set @update_date = ''
            set @tracker = ' v1'

            if not exists (
                select top 1 1
                from information_schema.views v
                where table_schema = '${snakeSchema}'
                and table_name = '${snakeTable}'
                and v.view_definition like '%-- '+@update_date+' - '+@tracker+' --%'
            )
                begin
                    print('Creating view ${snakeSchema}.${snakeTable}');

                exec('

                    create or alter view ${snakeSchema}.vw_${snakeTable} 
                    as
                    -- '+@update_date+' - '+@tracker+' --
                    (
                     select\n${formattedColumnList.join(",\n")} 
                     from ${snakeSchema}.${snakeTable};\n
                    ');

                end`
        );

    };

    const handleDownloadAll = () => {
        if (!jsonOutput) return;

        const today = getTodayFormatted();
        const snakeSchema = toSnakeCase(schema);
        const snakeTable = toSnakeCase(tableName);

        downloadFile(
            `${snakeSchema}_${snakeTable}_config_${today}.json`,
            jsonOutput
        );
        downloadFile(
            `${snakeSchema}_${snakeTable}_mapping_${today}.txt`,
            mappingOutput
        );
        downloadFile(
            `${snakeSchema}_${snakeTable}_table_ddl_${today}.txt`,
            silverSQLOutput
        );
        downloadFile(
            `${snakeSchema}_${snakeTable}_view_ddl_${today}.txt`,
            silverViewSQLOutput
        );
    };

    return (
        <div style={{ padding: 30 }}>
            <h2>Snowflake Table Script Generator</h2>

            <div>
                <label>Schema:</label>
                <input value={schema} onChange={e => setSchema(e.target.value)} />
                <label style={{ marginLeft: 20 }}>Table Name:</label>
                <input value={tableName} onChange={e => setTableName(e.target.value)} />
            </div>

            <div style={{ marginTop: 15 }}>
                <label>CDC Type:</label>
                <select value={cdcType} onChange={e => setCdcType(e.target.value)}>
                    {cdcOptions.map(c => (
                        <option key={c} value={c}>{c}</option>
                    ))}
                </select>
            </div>

            <div style={{ marginTop: 15 }}>
                <label>Upload CSV/TXT:</label>
                <input type="file" accept=".csv,.txt,.parquet" onChange={handleFileUpload} />
            </div>

            <h3>Columns</h3>

            <div style={{ display: "flex", gap: 20 }}>
                <div>
                    <h4>Raw Columns</h4>
                    <textarea
                        rows={15}
                        cols={40}
                        value={rawColumns}
                        onChange={e => setRawColumns(e.target.value)}
                    />
                </div>

                <div style={{ alignSelf: "center" }}>
                    <button onClick={handleFormatColumns}>* Format *</button>
                </div>

                <div>
                    <h4>Formatted Columns</h4>
                    <textarea
                        rows={15}
                        cols={40}
                        value={formattedColumns}
                        onChange={e => setFormattedColumns(e.target.value)}
                    />
                </div>
            </div>

            {warnings.length > 0 && (
                <div style={{ color: "red", marginTop: 15 }}>
                    <strong>Validation Warnings:</strong>
                    <ul>
                        {warnings.map((w, i) => (
                            <li key={i}>{w}</li>
                        ))}
                    </ul>
                </div>
            )}

            {formattedColumnList.length > 0 && (
                <>
                    <h3>Column Governance</h3>
                    <table border={1} cellPadding={5}>
                        <thead>
                            <tr>
                                <th>Column</th>
                                <th>Data Type</th>
                                <th>Nullable</th>
                                <th>Classification</th>
                                <th>Masking</th>
                                <th>Hash</th>
                                <th>Encrypt</th>
                            </tr>
                        </thead>
                        <tbody>
                            {governance.map(col => (
                                <tr key={col.column}>
                                    <td>{col.column}</td>

                                    <td>
                                        <input
                                            list="datatype-options"
                                            value={col.dataType}
                                            onChange={e =>
                                                setGovernanceOverrides(prev => ({
                                                    ...prev,
                                                    [col.column]: {
                                                        ...prev[col.column],
                                                        dataType: e.target.value
                                                    }
                                                }))
                                            }
                                        />
                                    </td>

                                    <td>
                                        <select
                                            value={col.nullable}
                                            onChange={e =>
                                                setGovernanceOverrides(prev => ({
                                                    ...prev,
                                                    [col.column]: {
                                                        ...prev[col.column],
                                                        nullable: e.target.value
                                                    }
                                                }))
                                            }
                                        >
                                            {nullableOptions.map(opt => (
                                                <option key={opt} value={opt}>{opt}</option>
                                            ))}
                                        </select>
                                    </td>

                                    <td>
                                        <select
                                            value={col.classification}
                                            onChange={e =>
                                                setGovernanceOverrides(prev => ({
                                                    ...prev,
                                                    [col.column]: {
                                                        ...prev[col.column],
                                                        classification: e.target.value
                                                    }
                                                }))
                                            }
                                        >
                                            {classificationOptions.map(opt => (
                                                <option key={opt} value={opt}>{opt}</option>
                                            ))}
                                        </select>
                                    </td>

                                    <td>
                                        <select
                                            value={col.masking}
                                            onChange={e =>
                                                setGovernanceOverrides(prev => ({
                                                    ...prev,
                                                    [col.column]: {
                                                        ...prev[col.column],
                                                        masking: e.target.value
                                                    }
                                                }))
                                            }
                                        >
                                            {maskingOptions.map(opt => (
                                                <option key={opt} value={opt}>{opt}</option>
                                            ))}
                                        </select>
                                    </td>

                                    <td>
                                        <input
                                            type="checkbox"
                                            checked={col.hash}
                                            onChange={e =>
                                                setGovernanceOverrides(prev => ({
                                                    ...prev,
                                                    [col.column]: {
                                                        ...prev[col.column],
                                                        hash: e.target.checked
                                                    }
                                                }))
                                            }
                                        />
                                    </td>

                                    <td>
                                        <input
                                            type="checkbox"
                                            checked={col.encrypt}
                                            onChange={e =>
                                                setGovernanceOverrides(prev => ({
                                                    ...prev,
                                                    [col.column]: {
                                                        ...prev[col.column],
                                                        encrypt: e.target.checked
                                                    }
                                                }))
                                            }
                                        />
                                    </td>
                                </tr>
                            ))}
                        </tbody>
                    </table>

                    <datalist id="datatype-options">
                        {dataTypeOptions.map(dt => <option key={dt} value={dt} />)}
                    </datalist>

                    <div style={{ marginTop: 20 }}>
                        <label>Primary Key(s):</label>
                        <select
                            multiple
                            value={primaryKeys}
                            onChange={e =>
                                setPrimaryKeys(Array.from(e.target.selectedOptions, opt => opt.value))
                            }
                        >
                            {formattedColumnList.map(col => (
                                <option key={col} value={col}>{col}</option>
                            ))}
                        </select>
                    </div>

                    <div style={{ marginTop: 20 }}>
                        <button onClick={handleGenerate}>Generate Scripts</button>
                        <button onClick={handleDownloadAll} style={{ marginLeft: 15 }}>
                            Save All Scripts
                        </button>
                    </div>
                </>
            )}

            {(jsonOutput || mappingOutput || silverSQLOutput) && (
                <div style={{ marginTop: 30 }}>
                    <div style={{ marginBottom: 10 }}>
                        <button onClick={() => setActiveTab("json")}>Table JSON</button>
                        <button onClick={() => setActiveTab("mapping")} style={{ marginLeft: 10 }}>
                            Column Mapping
                        </button>
                        <button onClick={() => setActiveTab("ddl")} style={{ marginLeft: 10 }}>
                            silver Table DDL
                        </button>
                        <button onClick={() => setActiveTab("view")} style={{ marginLeft: 10 }}>
                            silver View DDL
                        </button>
                    </div>

                    {activeTab === "json" && (
                        <textarea rows={25} cols={120} value={jsonOutput} readOnly />
                    )}
                    {activeTab === "mapping" && (
                        <textarea rows={25} cols={120} value={mappingOutput} readOnly />
                    )}
                    {activeTab === "ddl" && (
                        <textarea rows={25} cols={120} value={silverSQLOutput} readOnly />
                    )}
                    {activeTab === "view" && (
                        <textarea rows={25} cols={120} value={silverViewSQLOutput} readOnly />
                    )}
                </div>
            )}
        </div>
    );
}